export const GET_IMAGES = 'GET_IMAGES';
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const GET_HOME_CONTENT = 'GET_HOME_CONTENT';
export const GET_ABOUT_CONTENT = 'GET_ABOUT_CONTENT';
export const GET_CONTACT_CONTENT = 'GET_CONTACT_CONTENT';
